name: Build Python Releases

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v3
    - name: Preflight
      run: |
        brew install pkg-config
    - name: Download and extract Python source
      run: |
        wget -q https://www.python.org/ftp/python/3.12.1/Python-3.12.1.tgz
        tar -xzf Python-3.12.1.tgz
    - name: Create support folders
      run: |
        mkdir ~/Universal/
        mkdir ~/Universal/other-sources/
    - name: Apply patches
      run: |
        patch Python-3.12.1/Mac/BuildScript/build-installer.py /Users/runner/work/cpython-binaries-macos/cpython-binaries-macos/FixError530.patch
    - name: Run build script
      run: |
        cd Python-3.12.1/Mac/BuildScript/
        # https://bugs.python.org/issue46975
        brew remove --ignore-dependencies gettext
        python3 build-installer.py --dep-target=10.9 --universal-archs=universal2 --build-dir=/Users/runner/Universal/work
        export HOMEBREW_NO_AUTO_UPDATE=1
        export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
        brew install gettext
    - name: Create flat package
      run: |
        mkdir /Users/runner/work/cpython-binaries-macos/cpython-binaries-macos/output
        python3 /Users/runner/work/cpython-binaries-macos/cpython-binaries-macos/Create-Flat-Installer.py ~/Universal/work/installer/Python.mpkg /Users/runner/work/cpython-binaries-macos/cpython-binaries-macos/output/

    - name: Upload package
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Python
        path: /Users/runner/work/cpython-binaries-macos/cpython-binaries-macos/output/*.pkg
