name: Build Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  build:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v3
    - name: Preflight
      run: |
        brew install pkg-config
        # https://bugs.python.org/issue46975
        brew remove --ignore-dependencies gettext
    - name: Download and extract Python source
      run: |
        wget -q https://www.python.org/ftp/python/3.12.1/Python-3.12.1.tgz
        tar -xzf Python-3.12.1.tgz
    - name: Create support folders
      run: |
        mkdir ~/Universal/
        mkdir ~/Universal/other-sources/
    - name: Apply patches
      run: |
        patch Python-3.12.1/Mac/BuildScript/build-installer.py /Users/runner/work/cpython-binaries-macos/cpython-binaries-macos/FixError530.patch
    - name: Run build script
      run: |
        cd Python-3.12.1/Mac/BuildScript/
        python3 build-installer.py --dep-target=10.9 --universal-archs=universal2 --build-dir=/Users/runner/Universal/work
    - name: Upload disk image
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Discord Legacy
        path: ~/Universal/work/diskimage/*.dmg
